### ISSUE TITLE
치르닉스로 워크 실행시 오류

### ISSUE THREAD

**Issue by TERRIA3313** [BlacklightsC/OpenCirnix#2]
치르닉스로 워크를 실행하려고 하면 아래와 같은 오류가 뜹니다.
![image](https://user-images.githubusercontent.com/16536716/91714397-99867800-ebc6-11ea-821c-936128b9db6f.png)

**Comment by BlacklightsC** [comment]
M16Tool이 또 사고를 쳤군요...
%APPDATA%\Cirnix\JNService 내에 모든 파일을 삭제하고 실행을 해보면 아마 제대로 되실겁니다.

**Comment by Cindry-enivid** [comment]
> M16Tool이 또 사고를 쳤군요...
> %APPDATA%\Cirnix\JNService 내에 모든 파일을 삭제하고 실행을 해보면 아마 제대로 되실겁니다.

감사합니다 ㅠㅠ
어제 워크 접속이 안대길래 m16툴 들어갔더니 뭘 설치하더니만.,.,
저거 떄문이였군요..
